name: diamnod
channels:
  - pytorch
  - conda-forge
  - anaconda
  - menpo
dependencies:
  - python=3.10
  - wandb=0.17
  - hydra-core=1.3
  - hydra-submitit-launcher=1.2
  - hydra-colorlog=1.2
  # For mujoco
  - glew
  - mesalib
  - mesa-libgl-cos6-x86_64 # Needed on LUMI for osmesa?
  - glfw3
  - pip
  - pip:
      - torch==2.5.0+rocm6.2
      - torchvision==0.20.0+rocm6.2
      - --extra-index-url https://download.pytorch.org/whl/rocm6.2
      - vector_quantize_pytorch
      - info-nce-pytorch
      - gymnasium==0.29.1
      - ale-py==0.9.0
      - h5py==3.11.0
      - huggingface-hub==0.17.2
      - numpy==1.26.0
      - opencv-python==4.10.0.84
      - pillow==10.3.0
      - pygame==2.5.2
      - torcheval==0.0.7
      - tqdm==4.66.4
